version: '3.8'

# Common configuration that will be applied to all services
x-common-variables: &common-variables
  VITE_APP_VERSION: 1.0.0

services:
  # Frontend application - Development
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.multi-env
      args:
        NODE_ENV: development
        VITE_API_URL: http://api-dev:3000/api
        VITE_APP_ENVIRONMENT: development
    container_name: accounting-dashboard-frontend-dev
    ports:
      - "8080:80"
    depends_on:
      - api-dev
    networks:
      - app-network-dev
    environment:
      <<: *common-variables
      VITE_API_URL: http://api-dev:3000/api
      VITE_APP_ENVIRONMENT: development
      VITE_APP_NAME: Simple Accounting Dashboard (DEV)
      VITE_FEATURE_DEBUG_TOOLS: 'true'
      VITE_FEATURE_ADMIN_PANEL: 'true'
      VITE_FEATURE_DARK_MODE: 'true'
      VITE_AUTH_REQUIRE_EMAIL_VERIFICATION: 'false'
      VITE_AUTH_TOKEN_EXPIRATION: 120
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - dev

  # Frontend application - Staging
  frontend-staging:
    build:
      context: .
      dockerfile: Dockerfile.multi-env
      args:
        NODE_ENV: production
        VITE_API_URL: https://staging-api.example.com/api
        VITE_APP_ENVIRONMENT: staging
    container_name: accounting-dashboard-frontend-staging
    ports:
      - "8081:80"
    networks:
      - app-network-staging
    environment:
      <<: *common-variables
      VITE_API_URL: https://staging-api.example.com/api
      VITE_APP_ENVIRONMENT: staging
      VITE_APP_NAME: Simple Accounting Dashboard (STAGING)
      VITE_FEATURE_DEBUG_TOOLS: 'true'
      VITE_FEATURE_ADMIN_PANEL: 'true'
      VITE_FEATURE_DARK_MODE: 'true'
      VITE_ANALYTICS_ENABLED: 'true'
      VITE_ANALYTICS_ID: UA-STAGING-ID
      VITE_AUTH_REQUIRE_EMAIL_VERIFICATION: 'true'
      VITE_AUTH_TOKEN_EXPIRATION: 60
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    profiles:
      - staging

  # Frontend application - Production
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile.multi-env
      args:
        NODE_ENV: production
        VITE_API_URL: https://api.example.com/api
        VITE_APP_ENVIRONMENT: production
    container_name: accounting-dashboard-frontend-prod
    ports:
      - "80:80"
    networks:
      - app-network-prod
    environment:
      <<: *common-variables
      VITE_API_URL: https://api.example.com/api
      VITE_APP_ENVIRONMENT: production
      VITE_APP_NAME: Simple Accounting Dashboard
      VITE_FEATURE_DEBUG_TOOLS: 'false'
      VITE_FEATURE_ADMIN_PANEL: 'true'
      VITE_FEATURE_DARK_MODE: 'true'
      VITE_ANALYTICS_ENABLED: 'true'
      VITE_ANALYTICS_ID: UA-PRODUCTION-ID
      VITE_AUTH_REQUIRE_EMAIL_VERIFICATION: 'true'
      VITE_AUTH_TOKEN_EXPIRATION: 30
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    profiles:
      - prod

  # Mock API server for development
  api-dev:
    image: node:18-alpine
    container_name: accounting-dashboard-api-dev
    working_dir: /app
    volumes:
      - ./mock-api:/app
    command: >
      sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network-dev
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRATION=1h
      - REFRESH_TOKEN_EXPIRATION=7d
    profiles:
      - dev

# Networks for different environments
networks:
  app-network-dev:
    driver: bridge
  app-network-staging:
    driver: bridge
  app-network-prod:
    driver: bridge